services:

  # Run the application
  app:
    build:
      context: .
      target: runtime
    image: process-fork:latest

  # Run tests only (exits after tests complete)
  test:
    build:
      context: .
      target: tester
    image: process-fork:test
